"""add sanctions_entries table

Revision ID: afe372661dab
Revises: 05e0e3f24c1e
Create Date: 2026-09-02 14:29:26.383264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe372661dab'
down_revision: Union[str, Sequence[str], None] = '05e0e3f24c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanctions_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanctions_entries_name'), 'sanctions_entries', ['name'], unique=False)
    # ### end Alembic commands ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.execute(
        "CREATE INDEX idx_sanctions_entries_name_trgm ON sanctions_entries USING gin (name gin_trgm_ops);")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sanctions_entries_name'), table_name='sanctions_entries')
    op.drop_table('sanctions_entries')
    op.execute("DROP INDEX IF EXISTS idx_sanctions_entries_name_trgm;")
    # ### end Alembic commands ###
